sudo: required
language: python
services:
- docker
script: docker build -t don-bot .
after_script: docker run -it --rm don-bot /bin/sh -c "git checkout master; codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN --debug"
